spring.ai.bedrock.converse.chat.options.model=amazon.nova-lite-v1:0
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=ping
